### ISSUE TITLE
compile issue after clean clone

### ISSUE THREAD

**Issue by JohanZoidberg** [TiarkRompf/replhtml#4]
Great idea - i want to run it:
On a much used scala 2.8 dev machine..
after a flesh clone and sbt update; sbt compile; sbt run:

[info] == run ==
[info] Running ch.epfl.lamp.replhtml.ReplMain
/home/user/wa\replhtml2\lib_managed\scala_2.8.0\compile\jetty-servlet-7.1.6.v20100715.jar;/home/user\replhtml2\lib_managed\scala_2.8.0\compile\jetty-webapp-7.1.6.v20100715.jar;/home/user/wa\replhtml2\target\scala_2.8.0\classes;/home/user/wa/\replhtml2\lib_managed\scala_2.8.0\compile\jetty-xml-7.1.6.v20100715.jar;/home/user/wa/replhtml2\lib_managed\scala_2.8.0\compile\jetty-continuation-7.1.6.v20100715.jar;/home/user/wa/\replhtml2\lib_managed\scala_2.8.0\compile\servlet-api-2.5.jar;/home/user/wa\replhtml2\lib_managed\scala_2.8.0\compile\jetty-security-7.1.6.v20100715.jar;/home/user/\wa\replhtml2\lib_managed\scala_2.8.0\compile\jetty-util-7.1.6.v20100715.jar;/home/user/wa/\replhtml2\lib_managed\scala_2.8.0\compile\jetty-http-7.1.6.v20100715.jar;/home/user/wa/\replhtml2\lib_managed\scala_2.8.0\compile\jetty-server-7.1.6.v20100715.jar;/home/user/wa/\replhtml2\lib_managed\scala_2.8.0\compile\jetty-websocket-7.1.6.v20100715.jar;/home/user/wa/\replhtml2\project\boot\scala-2.8.0\lib\scala-library.jar;/home/user/wa\replhtml2\lib_managed\scala_2.8.0\compile\jetty-io-7.1.6.v20100715.jar;/home/user/wa\replhtml2\project\boot\scala-2.8.0\lib\scala-compiler.jar:
EXTRA:null
<console>:5: error: value tools is not a member of package scala
       import scala.tools.nsc._
                    ^
<script>:3: error: value tools is not a member of package scala
  var value: scala.tools.nsc.Interpreter = _
                   ^
<script>:4: error: value tools is not a member of package scala
  def set(x: Any) = value = x.asInstanceOf[scala.tools.nsc.Interpreter]
                                                 ^
java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:185)
        at scala.None$.get(Option.scala:183)
        at scala.tools.nsc.Interpreter.bind(Interpreter.scala:622)
        at scala.tools.nsc.Interpreter$$anonfun$unleash$1.apply(Interpreter.scala:1031)
        at scala.tools.nsc.Interpreter$$anonfun$unleash$1.apply(Interpreter.scala:1029)
        at scala.tools.nsc.Interpreter$$anonfun$beQuietDuring$2.apply(Interpreter.scala:171)
        at scala.util.control.Exception$Catch.apply(Exception.scala:79)
        at scala.tools.nsc.Interpreter.beQuietDuring(Interpreter.scala:169)
        at scala.tools.nsc.Interpreter.unleash(Interpreter.scala:1029)
        at ch.epfl.lamp.replhtml.ReplServlet$$anon$2.unleash(ReplServlet.scala:28)
        at ch.epfl.lamp.replhtml.ReplServlet.<init>(ReplServlet.scala:30)
        at ch.epfl.lamp.replhtml.ReplMain$.main(ReplMain.scala:17)
        at ch.epfl.lamp.replhtml.ReplMain.main(ReplMain.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sbt.Run.run0(Run.scala:60)
        at sbt.Run.execute$1(Run.scala:47)
        at sbt.Run$$anonfun$run$2.apply(Run.scala:50)
        at sbt.Run$$anonfun$run$2.apply(Run.scala:50)
        at sbt.TrapExit$.executeMain$1(TrapExit.scala:33)
        at sbt.TrapExit$$anon$1.run(TrapExit.scala:42)
[info] == run ==
[error] Error running run: Nonzero exit code: 1

**Comment by TiarkRompf** [comment]
aah, windows. class path delimiter is ';' and not ':'. should be fixed now.

**Comment by JohanZoidberg** [comment]
works great now, ty
